---
- name: Rechercher les mises à jour et afficher le résultat
  hosts: all
  gather_facts: false
  tasks:
    - name: Recherche des mises à jour ...
      ansible.windows.win_updates:
        state: searched
      register: update_results

    - name: "Rapport des mises à jour disponible :"
      vars:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }} 
          {% endfor %}
      debug: 
        msg: "{{ msg.split('\n') }}"