---
- name: Installer toutes les mises à jour de sécurité, critiques et cumulatives
  hosts: all
  gather_facts: false
  tasks:
    - name: Installation des mises à jour ...
      ansible.windows.win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      become: true
      become_method: runas
      become_user: SYSTEM