---
- name: Installer une mise à jour particulière en fonction des nombres KB
  hosts: all
  gather_facts: false
  tasks:
    - name: Install all security updates with automatic reboots
      ansible.windows.win_updates:
        category_names:
        - SecurityUpdates
        accept_list:
        - KB4056892
        - KB4073117