---
- name: Installer toutes les mises à jour disponible sans redémarrage
  hosts: all
  gather_facts: false
  tasks:
    - name: Installation des mises à jour ...
      ansible.windows.win_updates:
        category_names: '*'
        reboot: false
